---
piVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m0s
  chart: rook-ceph
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: rook
  version: 1.14
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: rook-ceph
    namespace: rook-ceph
  #chart:
    #spec:
      #chart: rook-ceph
      #version: 1.14.x
      #sourceRef:
        #kind: HelmRepository
        #name: rook
        #namespace: flux-system
      #interval: 10m
  valuesFrom:
  - kind: ConfigMap
    name: rook-ceph-operator-values
