---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 30m
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1 # keep trying to remediate
  chart:
    spec:
      chart: rook-ceph
      version: 1.14.x
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
      interval: 10m
  valuesFrom:
  - kind: ConfigMap
    name: rook-ceph-operator-values
