---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: rook-ceph-operator-values
    files:
      - values.yaml=./values.yaml
