---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1tp0xhtfax7fxv55vcx7nx6tlp3yd2xszp4stxmn0h2su49t67yjqxwzag9"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1tp0xhtfax7fxv55vcx7nx6tlp3yd2xszp4stxmn0h2su49t67yjqxwzag9"
