apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:O+yUXQVI1kEkLRPM0IE2RBKvvIjgh1Okq+T5x2PyOK4=,iv:Uz7JsiDrFTBat2au5zvITniQbiQWHgc72JnaIEHc1bE=,tag:x/+Bx794Lsvp62AR6Ee7Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tp0xhtfax7fxv55vcx7nx6tlp3yd2xszp4stxmn0h2su49t67yjqxwzag9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOFpYdUxkUmNFOVlGNTVL
            ZXpNSUVBaEJLaVRMdWsvV3lKWU5Ja2FnYkJrCmN1UWFVM1A3TWRESldRMWZjRGx5
            dnJXd2xYdlNtRnFHNEFCajhhQ205cDAKLS0tIEdNNzlGVi9GRC9RVWpoRmdLOGt5
            Zk1TMnZCVGsrbml6MklrVy93VDZ2N1kKPFdANopjS+VOARplYVElskyzx4kjs3tA
            PWzxKSvhz2m01KaYQfyVBqgrnrxNVpEXdPIregnLt7xL305QMIvqow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-17T03:13:18Z"
    mac: ENC[AES256_GCM,data:twnc2aZwZWBP4kjQQBE458VD1YLZycm5JEOS+zH/9wldpBgGLJzU4DpF2l5rBI9d4vUaAAacvXLoPSazGaDSgSo4TecKLsUYUXk/bKvHzZ7QKN0JM0GtaF5icb6N+fFua3w7cWfhfg2VpWqRcihEjgXEglL0gA7X3riDhUvjTtk=,iv:QIYcgAbcLCDA4IhZN//Zh48d/Epw0aimTCL0NndRfzM=,tag:s1bgNssNsJs0GQZCKdOttQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
