---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name rook-ceph-operator
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kubernetes/apps/rook-ceph/rook-ceph/operator
  prune: false
  retryInterval: 20m0s
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  timeout: 15m0s
  wait: true
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: cephblockpools.ceph.rook.io
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
  - name: rook-ceph-operator
  targetNamespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/rook-ceph/rook-ceph/rook-ceph-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  prune: false
  timeout: 10m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
