---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name rook-ceph
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kubernetes/apps/rook-ceph/rook-ceph/operator
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: HelmRepository
    name: rook
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  timeout: 3m0s
  wait: true
  # healthChecks:
  # - apiVersion: apiextensions.k8s.io/v1
    # kind: CustomResourceDefinition
    # name: cephblockpools.ceph.rook.io
