apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tp0xhtfax7fxv55vcx7nx6tlp3yd2xszp4stxmn0h2su49t67yjqxwzag9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZDhaSFd6NkVFcllpNWl2
            RVdob1JiOEpuQ1ozRnRvcDlHVGQwUHhtM3l3CnQ3cUt2MS9reGhzTHJNRkJXeXM1
            cG9sQi9XWGU4VTRldHRKdjRwOVI5blEKLS0tIDgyMXdQaERIa3pJYUJCUHQwVDlR
            aWo3cXBZKzlWVmhZWWsvdmZOdlR3encKbmjZYVh3o6Sl3bQVC0KjOIb4hE13mqsO
            FzThq7AHR4AGaHU18ZBzIpxf90rY3p3X64RCMcudA7zzRQhk2yyTmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-17T03:13:18Z"
    mac: ENC[AES256_GCM,data:ArtBadopRs7qrzSzxQluM8tHshXd5bc8xc/2nNdZQ3wKOdQYtlhfVid/pRvIPvAkopwiZS6dTwDKYrEUmEwZ/684d2EJnnP5HI8u6niGeXzVqU0EYs9nApOjNvHBNIMyTh/rnCGtza/6A5ZVcOZjydaHXowsVGYlmbYqWtRhU+Q=,iv:Whme1NAFsrUlK7l3Yba477bXv430NkWXnCwkP03fGIk=,tag:t3o0f3zUfIa6zTs2YJwzRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
